export const productColumns = [
  { title: '農產品名稱', dataIndex: 'productName', key: 'productName' },
  { title: '原價', dataIndex: 'origialPrice', key: 'origialPrice' },
  { title: '促銷價', dataIndex: 'discountPrice', key: 'discountPrice' },
  { title: '庫存量', dataIndex: 'stock', key: 'stock' },
  { title: '上架時間', dataIndex: 'createTime', key: 'createTime' },
  { title: '商品狀態', dataIndex: 'productstatus', key: 'productstatus' },
];

export const productData = [
  {
    id: '001',
    productName: '甜蜜時光有機草莓',
    origialPrice: 500,
    discountPrice: 250,
    stock: 200,
    createTime: '2022/01/28',
    productstatus: '上架',
  },
  {
    id: '002',
    productName: '夏浪西瓜舞',
    origialPrice: 299,
    discountPrice: 199,
    stock: 20,
    createTime: '2023/12/25',
    productstatus: '上架',
  },
  {
    id: '003',
    productName: '極致芒果夏韻',
    origialPrice: 399,
    discountPrice: 300,
    stock: 130,
    createTime: '22023/10/05',
    productstatus: '未出貨',
  },
  {
    id: '004',
    productName: '夢幻柳橙夏悠',
    origialPrice: 350,
    discountPrice: 250,
    stock: 110,
    createTime: '2023/10/02',
    productstatus: '未出貨',
  },
  {
    id: '005',
    productName: '柳橙夏悠',
    origialPrice: 230,
    discountPrice: 150,
    stock: 60,
    createTime: '2023/11/02',
    productstatus: '未出貨',
  },
  {
    id: '006',
    productName: '甜蜜有機草莓',
    origialPrice: 430,
    discountPrice: 250,
    stock: 260,
    createTime: '2023/12/02',
    productstatus: '未出貨',
  },
];
