import { ReactNode } from 'react';
import { UseFormRegister, FieldErrors, RegisterOptions } from 'react-hook-form';
export type FormValues = {
  email: string;
  password: string;
  confirmPassword: string;
  userName: string;
  userPhone: string;
  address: string;
  identity: { value: string; label: string };
  nickName: string;
  gender: string;
  zip: string;
  datePicker: Date;
  idea: string;
  introduce: string;
  liveName: string;
  liveLink: string;
  startTime: string;
  endTime: string;
  productTitle: string;
  imageURL: string;
  productState: string;
  spec: string;
  smallWeight: string;
  smallOriginalPrice: string;
  smallPromotionPrice: string;
  smallStock: string;
  largeWeight: string;
  largeOriginalPrice: string;
  largePromotionPrice: string;
  largeStock: string;
  liveProduct: string;
  origin: string;
  storage: string;
  period: string;
  category: string;
  description: string;
  liveProductSpec: string;
  liveSpectialPrice: string;
  introduction: string;
  ProductToChat: string;
  county: { label: string; value: string };
  district: { label: string; value: string } | null;
};
export type DefaultInputProps = {
  type: 'email' | 'text' | 'password' | 'tel' | "number";
  labelText: string;
  inputText: string;
  icon?: ReactNode;
  id: keyof FormValues;
  register?: UseFormRegister<FormValues>;
  errors?: FieldErrors<FormValues>;
  rules: RegisterOptions;
  page?: string;
  globalStyle?: string;
  isdisabled?: boolean;
};

export type PersonInputProps = {
  type: 'email' | 'text' | 'password' | 'tel' | 'number';
  labelText: string;
  inputText: string;
  labelStyle?: string;
  inputStyle: string;
  id: keyof FormValues;
  register?: UseFormRegister<FormValues>;
  errors?: FieldErrors<FormValues>;
  rules?: RegisterOptions;
  isdisabled?: boolean;
  value?: string;
};

export type SearchInputProps = {
  headerVisible?: boolean;
  onClick?: () => void;
};